CREATE TABLE companies
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255),
    location VARCHAR(255)
);

INSERT INTO companies (name, location) VALUES ('Company1', 'New York');
INSERT INTO companies (name, location) VALUES ('Company2', 'Los Angeles');
INSERT INTO companies (name, location) VALUES ('Company3', 'Chicago');
INSERT INTO companies (name, location) VALUES ('Company4', 'San Diego');
INSERT INTO companies (name, location) VALUES ('Company5', 'Seattle');
INSERT INTO companies (name, location) VALUES ('Company6', 'Houston');
INSERT INTO companies (name, location) VALUES ('Company7', 'San Francisco');
INSERT INTO companies (name, location) VALUES ('Company8', 'Dallas');
INSERT INTO companies (name, location) VALUES ('Company9', 'Boston');
INSERT INTO companies (name, location) VALUES ('Company10', 'Miami');